version: '3.7'

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: username
            MONGO_INITDB_ROOT_PASSWORD: password
        volumes:
            - '/home/mongo/_data:/data/db'
        networks:
            screener:

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: creativ360
            ME_CONFIG_MONGODB_ADMINPASSWORD: password
        networks:
            screener:
networks:
    screener:
        external:
            name: covidscreener-network
